services:
  frontend:
    container_name: foodgram-front
    image: doonyanikitin/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/

  db:
    container_name: foodgram-db
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  django:
    container_name: foodgram-django
    image: doonyanikitin/foodgram_backend:latest
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput && python manage.py import_csv &&
             gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
