# Generated by Django 3.2.25 on 2024-10-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourites',
            name='unigue_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='shopcart',
            name='unigue_shopping_cart',
        ),
        migrations.AddConstraint(
            model_name='favourites',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='unigue_favorite'),
        ),
        migrations.AddConstraint(
            model_name='shopcart',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='unigue_shopping_cart'),
        ),
    ]
