# Generated by Django 5.0.4 on 2024-10-12 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0020_alter_favorite_options_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        10000, message="Время должно быть не больше 10000 минут"
                    ),
                    django.core.validators.MinValueValidator(
                        1, message="Время должно быть не меньше 1 минуты"
                    ),
                ],
                verbose_name="Время готовки",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        10000, message="Количество не может превышать 10000"
                    ),
                    django.core.validators.MinValueValidator(
                        1, message="Количество не может быть меньше 1"
                    ),
                ],
                verbose_name="Кол-во",
            ),
        ),
    ]
