# Generated by Django 3.2.25 on 2024-10-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='foodgramuser',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unigue_together'),
        ),
    ]
